=== Tave21/Computer-Engineering-UniPi/Master Projects/DSMT - FleetFra/src/main/fleetfra_chin/apps/fleetfra_chin/json_references/json_schema/start_game_client_message_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "game_id": {
      "type": "string"
    },
    "player": {
      "type": "string"
    },
    "type_request": {
      "type": "string",
      "enum": ["start_game_client"]
    },
    "player_battlefield": {
      "type": "array",
      "minItems": 1,
      "maxItems": 100,
      "items": {
        "type": "object",
        "required": ["row", "col", "value"],
        "properties": {
          "row": {
            "type": "integer",
            "minimum": 0,
            "maximum": 9
          },
          "col": {
            "type": "integer",
            "minimum": 0,
            "maximum": 9
          },
          "value": {
            "type": "integer",
            "enum": [0, 1, 2, 3, -1]
          }
        }
      }
    }
  },
  "required": ["game_id", "player", "type_request", "player_battlefield"],
  "additionalProperties": false
}

=== Tave21/Computer-Engineering-UniPi/Master Projects/src/main/fleetfra_chin/apps/fleetfra_chin/json_references/json_examples/start_game_client_message_example.json
{
  "game_id": "kRf4nhR6aLKm3nNmhJdq",
  "player": "player111",
  "type_request": "start_game_client",
  "player_battlefield": [
    {
      "col": 0,
      "value": 0,
      "row": 0
    },
    {
      "col": 1,
      "value": 0,
      "row": 0
    },
    {
      "col": 2,
      "value": 0,
      "row": 0
    },
    {
      "col": 3,
      "value": 0,
      "row": 0
    },
    {
      "col": 4,
      "value": 0,
      "row": 0
    },
    {
      "col": 5,
      "value": 0,
      "row": 0
    },
    {
      "col": 6,
      "value": 0,
      "row": 0
    },
    {
      "col": 7,
      "value": 0,
      "row": 0
    },
    {
      "col": 8,
      "value": 0,
      "row": 0
    },
    {
      "col": 9,
      "value": 0,
      "row": 0
    },
    {
      "col": 0,
      "value": 0,
      "row": 1
    },
    {
      "col": 1,
      "value": 0,
      "row": 1
    },
    {
      "col": 2,
      "value": 0,
      "row": 1
    },
    {
      "col": 3,
      "value": 0,
      "row": 1
    },
    {
      "col": 4,
      "value": 0,
      "row": 1
    },
    {
      "col": 5,
      "value": 0,
      "row": 1
    },
    {
      "col": 6,
      "value": 0,
      "row": 1
    },
    {
      "col": 7,
      "value": 0,
      "row": 1
    },
    {
      "col": 8,
      "value": 0,
      "row": 1
    },
    {
      "col": 9,
      "value": 0,
      "row": 1
    },
    {
      "col": 0,
      "value": 0,
      "row": 2
    },
    {
      "col": 1,
      "value": 0,
      "row": 2
    },
    {
      "col": 2,
      "value": 0,
      "row": 2
    },
    {
      "col": 3,
      "value": 1,
      "row": 2
    },
    {
      "col": 4,
      "value": 0,
      "row": 2
    },
    {
      "col": 5,
      "value": 0,
      "row": 2
    },
    {
      "col": 6,
      "value": 0,
      "row": 2
    },
    {
      "col": 7,
      "value": 0,
      "row": 2
    },
    {
      "col": 8,
      "value": 0,
      "row": 2
    },
    {
      "col": 9,
      "value": 0,
      "row": 2
    },
    {
      "col": 0,
      "value": 0,
      "row": 3
    },
    {
      "col": 1,
      "value": 0,
      "row": 3
    },
    {
      "col": 2,
      "value": 0,
      "row": 3
    },
    {
      "col": 3,
      "value": 1,
      "row": 3
    },
    {
      "col": 4,
      "value": 0,
      "row": 3
    },
    {
      "col": 5,
      "value": 0,
      "row": 3
    },
    {
      "col": 6,
      "value": 0,
      "row": 3
    },
    {
      "col": 7,
      "value": 0,
      "row": 3
    },
    {
      "col": 8,
      "value": 0,
      "row": 3
    },
    {
      "col": 9,
      "value": 0,
      "row": 3
    },
    {
      "col": 0,
      "value": 0,
      "row": 4
    },
    {
      "col": 1,
      "value": 0,
      "row": 4
    },
    {
      "col": 2,
      "value": 0,
      "row": 4
    },
    {
      "col": 3,
      "value": 1,
      "row": 4
    },
    {
      "col": 4,
      "value": 0,
      "row": 4
    },
    {
      "col": 5,
      "value": 0,
      "row": 4
    },
    {
      "col": 6,
      "value": 0,
      "row": 4
    },
    {
      "col": 7,
      "value": 0,
      "row": 4
    },
    {
      "col": 8,
      "value": 0,
      "row": 4
    },
    {
      "col": 9,
      "value": 0,
      "row": 4
    },
    {
      "col": 0,
      "value": 0,
      "row": 5
    },
    {
      "col": 1,
      "value": 0,
      "row": 5
    },
    {
      "col": 2,
      "value": 0,
      "row": 5
    },
    {
      "col": 3,
      "value": 0,
      "row": 5
    },
    {
      "col": 4,
      "value": 0,
      "row": 5
    },
    {
      "col": 5,
      "value": 0,
      "row": 5
    },
    {
      "col": 6,
      "value": 0,
      "row": 5
    },
    {
      "col": 7,
      "value": 0,
      "row": 5
    },
    {
      "col": 8,
      "value": 0,
      "row": 5
    },
    {
      "col": 9,
      "value": 0,
      "row": 5
    },
    {
      "col": 0,
      "value": 0,
      "row": 6
    },
    {
      "col": 1,
      "value": 0,
      "row": 6
    },
    {
      "col": 2,
      "value": 0,
      "row": 6
    },
    {
      "col": 3,
      "value": 0,
      "row": 6
    },
    {
      "col": 4,
      "value": 0,
      "row": 6
    },
    {
      "col": 5,
      "value": 1,
      "row": 6
    },
    {
      "col": 6,
      "value": 0,
      "row": 6
    },
    {
      "col": 7,
      "value": 0,
      "row": 6
    },
    {
      "col": 8,
      "value": 0,
      "row": 6
    },
    {
      "col": 9,
      "value": 0,
      "row": 6
    },
    {
      "col": 0,
      "value": 1,
      "row": 7
    },
    {
      "col": 1,
      "value": 1,
      "row": 7
    },
    {
      "col": 2,
      "value": 1,
      "row": 7
    },
    {
      "col": 3,
      "value": 1,
      "row": 7
    },
    {
      "col": 4,
      "value": 1,
      "row": 7
    },
    {
      "col": 5,
      "value": 1,
      "row": 7
    },
    {
      "col": 6,
      "value": 0,
      "row": 7
    },
    {
      "col": 7,
      "value": 0,
      "row": 7
    },
    {
      "col": 8,
      "value": 0,
      "row": 7
    },
    {
      "col": 9,
      "value": 0,
      "row": 7
    },
    {
      "col": 0,
      "value": 0,
      "row": 8
    },
    {
      "col": 1,
      "value": 0,
      "row": 8
    },
    {
      "col": 2,
      "value": 0,
      "row": 8
    },
    {
      "col": 3,
      "value": 0,
      "row": 8
    },
    {
      "col": 4,
      "value": 0,
      "row": 8
    },
    {
      "col": 5,
      "value": 1,
      "row": 8
    },
    {
      "col": 6,
      "value": 0,
      "row": 8
    },
    {
      "col": 7,
      "value": 0,
      "row": 8
    },
    {
      "col": 8,
      "value": 0,
      "row": 8
    },
    {
      "col": 9,
      "value": 0,
      "row": 8
    },
    {
      "col": 0,
      "value": 0,
      "row": 9
    },
    {
      "col": 1,
      "value": 0,
      "row": 9
    },
    {
      "col": 2,
      "value": 0,
      "row": 9
    },
    {
      "col": 3,
      "value": 0,
      "row": 9
    },
    {
      "col": 4,
      "value": 0,
      "row": 9
    },
    {
      "col": 5,
      "value": 1,
      "row": 9
    },
    {
      "col": 6,
      "value": 0,
      "row": 9
    },
    {
      "col": 7,
      "value": 0,
      "row": 9
    },
    {
      "col": 8,
      "value": 0,
      "row": 9
    },
    {
      "col": 9,
      "value": 0,
      "row": 9
    }
  ]
}
