=== Tave21/Computer-Engineering-UniPi/Master Projects/SSE - Brain-Based Wheelchair/ingestion_system/Ingestion_Configuration/IngestionSystemConfigurationSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "missing_samples_threshold_interval": {
      "type": "integer",
      "minimum": 0
    },
    "current_phase": {
      "type": "string",
      "enum": ["development", "production", "evaluation"]
    },
    "production_sessions": {
      "type": "integer",
      "minimum": 0
    },
    "service": {
      "type": "boolean"
    },
    "evaluation_sessions": {
      "type": "integer",
      "minimum": 0
    },
    "ip_preparation": {
      "type": "string",
      "format": "ipv4"
    },
    "ip_evaluation": {
      "type": "string",
      "format": "ipv4"
    },
    "port_preparation": {
      "type": "integer",
      "minimum": 1,
      "maximum": 65535
    },
    "port_evaluation": {
      "type": "integer",
      "minimum": 1,
      "maximum": 65535
    },
    "ip_ingestion": {
      "type": "string",
      "format": "ipv4"
    },
    "port_ingestion": {
      "type": "integer",
      "minimum": 1,
      "maximum": 65535
    }
  },
  "required": [
    "missing_samples_threshold_interval",
    "current_phase",
    "production_sessions",
    "service",
    "evaluation_sessions",
    "ip_preparation",
    "ip_evaluation",
    "port_preparation",
    "port_evaluation",
    "ip_ingestion",
    "port_ingestion"
  ]
}

=== Tave21/Computer-Engineering-UniPi/Master Projects/SSE Project - Brain-Based-Wheelchair/SaveMos-Brain-Based-Wheelchair-Control-9adc2b8/ingestion_system/Ingestion_Configuration/IngestionSystemConfiguration.json
{
    "missing_samples_threshold_interval": 3,
    "current_phase": "development",
    "production_sessions": 25000,
    "service": true,
    "evaluation_sessions": 50,
    "ip_preparation": "127.0.0.1",
    "ip_evaluation": "93.67.96.103",
    "port_preparation": 5002,
    "port_evaluation": 5030,
    "ip_ingestion": "0.0.0.0",
    "port_ingestion": 5001
}
